namespace SpriteKind {
    export const Weapon = SpriteKind.create()
    export const Item = SpriteKind.create()
    export const Sheild = SpriteKind.create()
    export const Shield = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Item, function (sprite, otherSprite) {
    otherSprite.destroy()
    Sword = sprites.create(img`
        . a a a a . . . . . . . . . . . . . . . . . 
        . a a a a . e d d d d d d d d d d d d d d d 
        e a a a a f e d d d d d d d d d d d d . . . 
        . a a a a . e d d d d d d d d d d . . . . . 
        . . . . . . . . . . . . . . . . . . . . . . 
        `, SpriteKind.Weapon)
    WeaponEquip = 1
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (JC == 0) {
        PlayerGuy.vy = -250
        pause(200)
        JC += 1
    }
})
function SSAnim () {
    let SwordSwing: Sprite = null
    SwordSwing.setImage(img`
        ......1..................
        ......11.................
        .......11................
        .........1...............
        .........1...............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `)
    pause(50)
    SwordSwing.setImage(img`
        .....1...................
        ......11.................
        .......11................
        ........11...............
        ........11...............
        ........11...............
        .........1...............
        .........11..............
        .........11..............
        .........11..............
        .........1...............
        .........1...............
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `)
    pause(50)
    SwordSwing.setImage(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        ..........1..............
        ..........1..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        .........1...............
        ........1................
        ........1................
        .........................
        .........................
        .........................
        .........................
        `)
    pause(50)
    SwordSwing.setImage(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        ..........1..............
        ..........1..............
        ..........1..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        .........11..............
        ........111..............
        ........111..............
        ........11...............
        ........11...............
        .......111...............
        ......11.................
        `)
    pause(50)
    SwordSwing.setImage(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        ..........1..............
        ..........1..............
        .........11..............
        ........111..............
        ........111..............
        ........11...............
        ........11...............
        .......11................
        ......1..................
        `)
    pause(50)
    SwordSwing.setImage(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .......11................
        ......1..................
        `)
    pause(50)
    SwordSwing.setImage(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .......11................
        ......1..................
        `)
    pause(50)
    SwordSwing.setImage(img`
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        .........................
        `)
}
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    Shield.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . 5 5 5 . . . . 
        . . . . 5 5 5 5 5 5 b b 5 . . . 
        . . . . 5 b b b d b b b 5 5 . . 
        . . . . 5 b b b d d b b b 5 . . 
        . . . . 5 b b b b d b b b 5 . . 
        . . . . 5 b b b b b d b b b 5 . 
        . . . . 5 5 b b b b d b b b 5 . 
        . . . . . 5 b b b b d d b b 5 . 
        . . . . . 5 b b b b b d b b 5 . 
        . . . . . 5 5 b b b b b d b 5 . 
        . . . . . . 5 5 b b b b d 5 5 . 
        . . . . . . . 5 5 b b b b 5 . . 
        . . . . . . . . 5 5 5 5 5 5 . . 
        . . . . . . . . . . . . . . . . 
        `)
    Shield.z = 3
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Sheild, function (sprite, otherSprite) {
    otherSprite.destroy()
    Shield = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . 5 5 5 5 5 5 5 . 
        . . . . . . . 5 b b b b b b 5 5 
        . . . . . . 5 5 b b b b b b b 5 
        . . . . . . 5 b b f b b b b b 5 
        . . . . . . 5 b b e f b b b b 5 
        . . . . . 5 b b a a a f b b b 5 
        . . . . . 5 b b a a a b b b 5 5 
        . . . . . 5 b f a a b b b b 5 . 
        . . . . . 5 b f f f b b b b 5 . 
        . . . . . 5 b b b b b b b 5 5 . 
        . . . . . 5 5 b b b b b 5 5 . . 
        . . . . . . 5 b b b b 5 5 . . . 
        . . . . . . 5 5 5 5 5 5 . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Shield)
    ShieldEquip = 1
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (WeaponEquip == 1 && Facing == 2) {
        Magic = sprites.createProjectileFromSprite(img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            .......9............
            ........6.666.66666.
            .9666.6.6666.6666.6.
            .......966.666.6....
            .......9............
            ....................
            ....................
            ....................
            ....................
            ....................
            `, PlayerGuy, 200, 0)
        Magic.setFlag(SpriteFlag.Ghost, true)
        animation.runImageAnimation(
        Magic,
        [img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            .......9............
            ........6.666.66666.
            .9666.6.6666.6666.6.
            .......966.666.6....
            .......9............
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            `,img`
            ....................
            .........9..........
            .........6..........
            .........6..........
            .........6..........
            ....................
            .........6..........
            .......99..9........
            ........666.........
            ........66..........
            .........66.........
            ........666.........
            ........6.6.........
            ........66..........
            .........66.........
            ........666.........
            .........66.........
            ..........6.........
            .........66.........
            ....................
            `,img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ............9.......
            ....6.666.669.......
            .6.6666.6666.6.6669.
            .66666.666.6........
            ............9.......
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            `,img`
            ....................
            .........66.........
            .........6..........
            .........66.........
            .........666........
            .........66.........
            ..........66........
            .........6.6........
            .........666........
            .........66.........
            ..........66........
            .........666........
            ........9..99.......
            ..........6.........
            ....................
            ..........6.........
            ..........6.........
            ..........6.........
            ..........9.........
            ....................
            `],
        100,
        true
        )
    }
    if (WeaponEquip == 1 && Facing == 1) {
        Magic = sprites.createProjectileFromSprite(img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ............9.......
            .66666.666.6........
            .6.6666.6666.6.6669.
            ....6.666.669.......
            ............9.......
            ....................
            ....................
            ....................
            ....................
            ....................
            `, PlayerGuy, -175, 0)
        Magic.setFlag(SpriteFlag.Ghost, true)
        animation.runImageAnimation(
        Magic,
        [img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ............9.......
            .66666.666.6........
            .6.6666.6666.6.6669.
            ....6.666.669.......
            ............9.......
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            `,img`
            ....................
            ..........9.........
            ..........6.........
            ..........6.........
            ..........6.........
            ....................
            ..........6.........
            ........9..99.......
            .........666........
            ..........66........
            .........66.........
            .........666........
            .........6.6........
            ..........66........
            .........66.........
            .........666........
            .........66.........
            .........6..........
            .........66.........
            ....................
            `,img`
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            .......9............
            .......966.666.6....
            .9666.6.6666.6666.6.
            ........6.666.66666.
            .......9............
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            ....................
            `,img`
            ....................
            .........66.........
            ..........6.........
            .........66.........
            ........666.........
            .........66.........
            ........66..........
            ........6.6.........
            ........666.........
            .........66.........
            ........66..........
            ........666.........
            .......99..9........
            .........6..........
            ....................
            .........6..........
            .........6..........
            .........6..........
            .........9..........
            ....................
            `],
        100,
        true
        )
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    Facing = 1
    FacingSH = 1
    if (WeaponEquip == 1) {
        Sword.setImage(img`
            . . . . . . . . . . . . . . . e . a a a a . 
            d d d d d d d d d d d d d d b e . a a a a . 
            . . . d d d d d d d d b b b b e f a a a a e 
            . . . . . d d d d d d d d d b e . a a a a . 
            . . . . . . . . . . . . . . . e . . . . . . 
            `)
        Sword.z = 1
    }
    if (ShieldEquip == 1) {
        Sword.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . 5 5 5 5 5 5 5 . . . . . . . . 
            5 5 b b b b b b 5 . . . . . . . 
            5 b b b b b b b 5 5 . . . . . . 
            5 b b b b b f b b 5 . . . . . . 
            5 b b b b f e b b 5 . . . . . . 
            5 b b b f a a a b b 5 . . . . . 
            5 5 b b b a a a b b 5 . . . . . 
            . 5 b b b a a a f b 5 . . . . . 
            . 5 b b b b f f f b 5 . . . . . 
            . 5 5 b b b b b b b 5 . . . . . 
            . . 5 5 b b b b b 5 5 . . . . . 
            . . . 5 5 b b b b 5 . . . . . . 
            . . . . 5 5 5 5 5 5 . . . . . . 
            . . . . . . . . . . . . . . . . 
            `)
        Sword.z = -2
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`EVENTTILE`, function (sprite, location) {
    Level = 1
    PlayerGuy.setPosition(29, 3)
    if (Level == 1) {
        scene.setBackgroundImage(img`
            ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
            cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccccbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccc
            ccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccc
            cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            cccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            ccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            ccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            ccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            ccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            ccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccc
            cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccc
            cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccc
            cccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccc
            ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccc
            ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccc
            ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccc
            ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccc
            ccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccc
            cccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccc
            cccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccc
            cccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccc
            ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccc
            ccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccc
            cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccc
            cccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccc
            ccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccc
            ccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccc
            cccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccc
            cccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccc
            ccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccc
            cccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccc
            cccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccc
            ccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccccccccccccccccccccccccccccccccccbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbcccccccccccccccccccc
            `)
        tiles.setTilemap(tilemap`level2`)
        SwordStationary = sprites.create(img`
            . . . . . 
            . d . . . 
            . d . . . 
            . d . . . 
            . d d . . 
            . d d . . 
            . d d d . 
            . d d d . 
            . d d d . 
            . d d d . 
            . d d d . 
            . d d d . 
            . d d d . 
            . d d d . 
            . d d d . 
            . d d d . 
            . e e e . 
            . . f . . 
            . . f . . 
            . . e . . 
            `, SpriteKind.Item)
        SwordStationary.setPosition(154, 160)
        Shield = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . 5 5 5 5 5 5 5 . 
            . . . . . . . 5 b b b b b b 5 5 
            . . . . . . 5 5 b b b b b b b 5 
            . . . . . . 5 b b f b b b b b 5 
            . . . . . . 5 b b e f b b b b 5 
            . . . . . 5 b b b e e f b b b 5 
            . . . . . 5 b b b e b b b b 5 5 
            . . . . . 5 b f e e b b b b 5 . 
            . . . . . 5 b f f f b b b b 5 . 
            . . . . . 5 b b b b b b b 5 5 . 
            . . . . . 5 5 b b b b b 5 5 . . 
            . . . . . . 5 b b b b 5 5 . . . 
            . . . . . . 5 5 5 5 5 5 . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Sheild)
        Shield.setPosition(130, 160)
        WeaponTester = sprites.create(img`
            . d . . . . . . . . . . . . . . 
            . d . . . . . . e . . . . . . . 
            . d . . . . . . e . . . . . . . 
            . d . . e . . . e . . . . . . . 
            e e e . e e . . e . e e e . . . 
            . f . . . e e e e e e . . . . . 
            . f e e e e . . . e . . . . . . 
            . f . . . e . . . e . . . . . . 
            . e . . . e . . . e . . . . . . 
            . . . . . e . . . e e . . . . . 
            . . . . . e e e e e e . . . . . 
            . . . . . e . . . . e . . . . . 
            . . . . . e . . . . e . . . . . 
            . . . . . e . . . . e . . . . . 
            . . . . . e . . d d d d d . . . 
            . . . . d d d d . . . . . . . . 
            `, SpriteKind.Enemy)
        WeaponTester.setPosition(250, 15)
        WeaponTester.ay = 1150
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    Facing = 2
    FacingSH = 2
    if (WeaponEquip == 1) {
        Sword.setImage(img`
            . a a a a . e . . . . . . . . . . . . . . . 
            . a a a a . e b d d d d d d d d d d d d d d 
            e a a a a f e b b b b d d d d d d d d . . . 
            . a a a a . e b d d d d d d d d d . . . . . 
            . . . . . . e . . . . . . . . . . . . . . . 
            `)
        Sword.z = 1
    }
    if (ShieldEquip == 1) {
        Shield.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . 5 5 5 5 5 5 5 . 
            . . . . . . . 5 b b b b b b 5 5 
            . . . . . . 5 5 b b b b b b b 5 
            . . . . . . 5 b b f b b b b b 5 
            . . . . . . 5 b b e f b b b b 5 
            . . . . . 5 b b a a a f b b b 5 
            . . . . . 5 b b a a a b b b 5 5 
            . . . . . 5 b f a a a b b b 5 . 
            . . . . . 5 b f f f b b b b 5 . 
            . . . . . 5 b b b b b b b 5 5 . 
            . . . . . 5 5 b b b b b 5 5 . . 
            . . . . . . 5 b b b b 5 5 . . . 
            . . . . . . 5 5 5 5 5 5 . . . . 
            . . . . . . . . . . . . . . . . 
            `)
        Shield.z = -2
    }
})
let projectile: Sprite = null
let WeaponTester: Sprite = null
let SwordStationary: Sprite = null
let FacingSH = 0
let Magic: Sprite = null
let Facing = 0
let Shield: Sprite = null
let WeaponEquip = 0
let Sword: Sprite = null
let ShieldEquip = 0
let JC = 0
let PlayerGuy: Sprite = null
let Level = 0
game.splash("Start Game?")
Level = 0
tiles.setTilemap(tilemap`level3`)
PlayerGuy = sprites.create(img`
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    a a a a a a a a a a a a a a a a 
    c a a a a a a a a a a a a a a a 
    c a a a a a a a a a a a a a a a 
    c a a a a a a a a a a a a a a a 
    c c c a a a a a a a a a a a a a 
    c c c c c c a a a a a a a a a a 
    c c c c c c c c c c c c c a a a 
    `, SpriteKind.Player)
PlayerGuy.setPosition(12, 77)
controller.moveSprite(PlayerGuy, 85, 0)
PlayerGuy.setStayInScreen(true)
scene.cameraFollowSprite(PlayerGuy)
let SwingVar = 0
JC = 0
PlayerGuy.z = 0
ShieldEquip = 0
forever(function () {
	
})
forever(function () {
    if (WeaponEquip == 1) {
        Sword.setPosition(PlayerGuy.x + 0, PlayerGuy.y + 4)
    }
    if (ShieldEquip == 1) {
        Shield.setPosition(PlayerGuy.x + 0, PlayerGuy.y + 4)
        Shield.z = -2
    }
})
forever(function () {
    PlayerGuy.ay = 1150
    if (JC == 1) {
        pause(300)
        JC += -1
    }
})
forever(function () {
    if (Level == 1) {
        projectile = sprites.createProjectileFromSprite(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . 2 2 . . . . . . . 
            . . . . . . . 2 2 . . . . . . . 
            . . . . . . . 2 2 . . . . . . . 
            . . . . 2 2 2 2 2 2 2 2 . . . . 
            . . . . 2 2 2 2 2 2 2 2 . . . . 
            . . . . . . . 2 2 . . . . . . . 
            . . . . . . . 2 2 . . . . . . . 
            . . . . . . . 2 2 . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, WeaponTester, -52, 0)
        pause(5000)
    }
})
